#!/bin/bash
# LobeHub - shared helpers

LOBE_DB_NAME="${LOBE_DB_NAME:-lobehub}"

gen_password() { openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 28; }
gen_secret()   { openssl rand -hex 16; }

ensure_jwks_key() {
    local lobe_image
    local xtrace_was_enabled=0

    # JWKS_KEY contains an RSA private key. Disable xtrace while generating and
    # persisting it so debug logs cannot expose the key.
    case "$-" in
        *x*)
            xtrace_was_enabled=1
            set +x
            ;;
    esac

    if [ -n "${jwks_key:-}" ]; then
        # Persist keys migrated from an existing .env file.
        ynh_app_setting_set --app="$app" --key=jwks_key --value="$jwks_key"
        [ "$xtrace_was_enabled" -eq 1 ] && set -x
        return 0
    fi

    lobe_image=$(docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" \
        config --images | grep '^lobehub/lobehub:' | head -n 1)
    if [ -z "$lobe_image" ]; then
        [ "$xtrace_was_enabled" -eq 1 ] && set -x
        ynh_die "Unable to determine the LobeHub image used to generate JWKS_KEY."
    fi

    jwks_key=$(docker run --rm --entrypoint node "$lobe_image" -e '
const crypto = require("node:crypto");
const { privateKey } = crypto.generateKeyPairSync("rsa", {
  modulusLength: 2048,
  publicExponent: 0x10001,
});
const jwk = privateKey.export({ format: "jwk" });
jwk.use = "sig";
jwk.kid = crypto.randomBytes(8).toString("hex");
jwk.alg = "RS256";
process.stdout.write(JSON.stringify({ keys: [jwk] }));
')

    if [ -z "$jwks_key" ]; then
        [ "$xtrace_was_enabled" -eq 1 ] && set -x
        ynh_die "JWKS_KEY generation returned an empty value."
    fi

    ynh_app_setting_set --app="$app" --key=jwks_key --value="$jwks_key"

    if [ "$xtrace_was_enabled" -eq 1 ]; then
        set -x
    fi

    ynh_print_info "Generated and securely stored the OIDC signing key."
}

build_app_url() {
    if [ "$path" = "/" ]; then
        APP_URL="https://${domain}"
    else
        APP_URL="https://${domain}${path}"
    fi
}

prepare_data_dirs() {
    mkdir -p "$data_dir/postgres"
    mkdir -p "$data_dir/rustfs"
    mkdir -p "$data_dir/redis"
    mkdir -p "$data_dir/searxng"

    chown -R "$app:$app" "$install_dir"
    chown -R "$app:$app" "$data_dir"

    # Official PostgreSQL and Redis containers run as numeric uid 999.
    chown -R 999:999 "$data_dir/postgres"
    chmod 700 "$data_dir/postgres"
    chown -R 999:999 "$data_dir/redis"
    chmod 750 "$data_dir/redis"

    # RustFS container runs as numeric uid 10001.
    chown -R 10001:10001 "$data_dir/rustfs"
    chmod 750 "$data_dir/rustfs"
}

# Never overwrite a database left by a failed install or restore.
check_postgres_data_dir_install() {
    local pg_dir="$data_dir/postgres"
    if [ -d "$pg_dir" ] && [ -n "$(ls -A "$pg_dir" 2>/dev/null)" ]; then
        ynh_die "Existing PostgreSQL data found in $pg_dir. Installation stopped to preserve it; restore or move it explicitly before retrying."
    fi
}

write_env_file() {
    cat > "$install_dir/.env" << ENV_EOF
# LobeHub - auto-generated by YunoHost installer
# Do not edit manually.

APP_URL=${APP_URL}
LOBE_PORT=${port}
RUSTFS_PORT=${port_rustfs_api}
RUSTFS_ADMIN_PORT=${port_rustfs_console}

# Database
LOBE_DB_NAME=lobehub
POSTGRES_PASSWORD=${postgres_password}

# Auth / Security
KEY_VAULTS_SECRET=${key_vaults_secret}
AUTH_SECRET=${auth_secret}
JWKS_KEY='${jwks_key}'

# S3 / RustFS
RUSTFS_ACCESS_KEY=${rustfs_access_key}
RUSTFS_SECRET_KEY=${rustfs_secret_key}
RUSTFS_LOBE_BUCKET=lobe
S3_PUBLIC_DOMAIN=${APP_URL}/s3

# Admin credentials (first-run setup)
AUTH_ADMIN_EMAIL=${admin_email}
AUTH_ADMIN_PASSWORD=${admin_password}
ENV_EOF

    chmod 600 "$install_dir/.env"
    chown root:root "$install_dir/.env"
}

write_bucket_policy() {
    # RustFS accepts the AWS S3 policy schema with "Id" (camelCase).
    cat > "$install_dir/bucket.config.json" << 'BUCKET_EOF'
{
  "Id": "",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": ["*"]
      },
      "Action": ["s3:GetObject"],
      "Resource": ["arn:aws:s3:::lobe/*"]
    }
  ]
}
BUCKET_EOF

    chown "$app:$app" "$install_dir/bucket.config.json"
    chmod 644 "$install_dir/bucket.config.json"
}

write_searxng_config() {
    # Ensure directory exists and is searchable
    mkdir -p "$data_dir/searxng"
    chown "$app:$app" "$data_dir/searxng"
    chmod 755 "$data_dir/searxng"

    cat > "$data_dir/searxng/settings.yml" << SEARXNG_EOF
use_default_settings: true

server:
  secret_key: "${searxng_secret}"
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"
  method: "POST"

search:
  safe_search: 0
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_theme: simple

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
SEARXNG_EOF

    chown "$app:$app" "$data_dir/searxng/settings.yml"
    chmod 644 "$data_dir/searxng/settings.yml"
}


write_compose_file() {
    sed \
        -e "s|__APP__|${app}|g" \
        -e "s|__INSTALL_DIR__|${install_dir}|g" \
        -e "s|__DATA_DIR__|${data_dir}|g" \
        -e "s|__PORT__|${port}|g" \
        -e "s|__PORT_RUSTFS_API__|${port_rustfs_api}|g" \
        -e "s|__PORT_RUSTFS_CONSOLE__|${port_rustfs_console}|g" \
        ../conf/docker-compose.yml > "$install_dir/docker-compose.yml"

    chown root:root "$install_dir/docker-compose.yml"
}

wait_for_lobehub() {
    local elapsed=0
    local max_wait="${1:-900}"
    while [ "$elapsed" -lt "$max_wait" ]; do
        if curl -sf "http://127.0.0.1:${port}/" >/dev/null 2>&1; then
            ynh_print_info "LobeHub is up and running."
            return 0
        fi

        # Early failure detection: inspect container states every ~30s.
        # If a dependency is clearly broken, abort now instead of waiting
        # the full timeout — the diagnostic output is what we actually
        # need to fix the problem, not the 15-minute wait.
        if [ $((elapsed % 30)) -eq 0 ] && [ "$elapsed" -gt 0 ]; then
            local lobe_state
            lobe_state=$(docker inspect --format='{{.State.Status}}' "${app}-lobe" 2>/dev/null || echo "missing")
            local pg_state
            pg_state=$(docker inspect --format='{{.State.Status}}' "${app}-postgres" 2>/dev/null || echo "missing")
            local rustfs_init_result
            rustfs_init_result=$(docker inspect --format='{{.State.Status}}:{{.State.ExitCode}}' "${app}-rustfs-init" 2>/dev/null || true)

            if [ -n "$rustfs_init_result" ] && [ "$rustfs_init_result" != "exited:0" ] &&
               [[ "$rustfs_init_result" == exited:* ]]; then
                ynh_print_warn "rustfs-init failed ($rustfs_init_result) after ${elapsed}s — aborting wait early."
                break
            fi

            # If lobe is restarting in a loop or has exited, it will never
            # become ready on its own — collect diagnostics and bail.
            if [ "$lobe_state" = "exited" ] || [ "$lobe_state" = "restarting" ]; then
                ynh_print_warn "lobe container is '$lobe_state' after ${elapsed}s — aborting wait early."
                break
            fi
            # If postgres is down/unhealthy, lobe can never connect.
            if [ "$pg_state" != "running" ] && [ "$pg_state" != "missing" ]; then
                ynh_print_warn "postgres container is '$pg_state' after ${elapsed}s — aborting wait early."
                break
            fi
        fi

        sleep 5
        elapsed=$((elapsed + 5))
    done

    # Health check failed — gather diagnostics
    ynh_print_warn "LobeHub did not respond on port ${port} within ${max_wait}s (elapsed: ${elapsed}s)."
    ynh_print_warn "=== systemctl status $app ==="
    systemctl status "$app" --no-pager || true
    ynh_print_warn "=== journalctl (last 200 lines) ==="
    journalctl -u "$app" -n 200 --no-pager || true
    ynh_print_warn "=== docker compose ps -a ==="
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" ps -a || true
    ynh_print_warn "=== docker logs (postgresql) ==="
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 postgresql 2>&1 || \
        docker logs --tail=200 "${app}-postgres" 2>&1 || true
    ynh_print_warn "=== docker logs (lobe) ==="
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 lobe 2>&1 || \
        docker logs --tail=200 "${app}-lobe" 2>&1 || true
    ynh_print_warn "=== docker logs (rustfs-init) ==="
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 rustfs-init 2>&1 || \
        docker logs --tail=200 "${app}-rustfs-init" 2>&1 || true
    ynh_die "Health check timed out. Check: journalctl -u $app and docker compose logs"
}

install_docker_ce() {
    # Skip if docker compose v2 is already available (from any source)
    if docker compose version &>/dev/null 2>&1; then
        ynh_print_info "Docker Compose v2 already available: $(docker compose version --short)"
        return 0
    fi

    ynh_print_info "Installing Docker CE (official repo - provides Compose v2)..."

    # Add Docker's official GPG key (do NOT remove existing packages — other YunoHost apps may depend on them)
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable docker --quiet
    systemctl start docker

    # Verify
    docker compose version || ynh_die "Docker Compose v2 installation failed"
    ynh_print_info "Docker CE + Compose v2 installed: $(docker compose version)"
}

# Remove Docker images used by this app (called from remove script)
cleanup_docker_images() {
    local project="$app"
    ynh_print_info "Removing Docker images for project $project..."

    if [ -f "$install_dir/docker-compose.yml" ]; then
        cd "$install_dir" || return 1
        # A separately managed gateway can share this Compose project. Do not
        # remove orphan containers or volumes during YunoHost rollback/removal.
        docker compose --project-name "$project" down --timeout 30 || true
        docker compose --project-name "$project" rm -f || true
        # Remove images referenced in the compose file
        docker images --filter "reference=lobehub/lobehub*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=pgvector/pgvector*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=redis:*-alpine" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=rustfs/rustfs*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=searxng/searxng*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
    fi
}

# Dump PostgreSQL database via docker exec (consistent backup)
dump_postgres() {
    local dump_file="$1"
    local temporary_dump="${dump_file}.tmp"

    ynh_print_info "Dumping PostgreSQL database..."
    if ! docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" \
        exec -T postgresql pg_dump -U postgres -d "$LOBE_DB_NAME" --clean --if-exists \
        > "$temporary_dump" 2>/dev/null; then
        rm -f "$temporary_dump"
        ynh_print_err "PostgreSQL dump failed."
        return 1
    fi

    if [ ! -s "$temporary_dump" ]; then
        rm -f "$temporary_dump"
        ynh_print_err "PostgreSQL dump is empty."
        return 1
    fi

    mv "$temporary_dump" "$dump_file"
}

# Restore PostgreSQL database from dump
restore_postgres() {
    local dump_file="$1"

    if [ ! -s "$dump_file" ]; then
        ynh_print_err "PostgreSQL dump is missing or empty: $dump_file"
        return 1
    fi

    ynh_print_info "Restoring PostgreSQL database from dump..."
    # pg_dump from older ParadeDB releases can place pg_search before vector
    # in CREATE order, and vector before pg_search in DROP order. Current
    # pg_search requires vector, so normalize those two extension statements
    # while streaming the dump without changing the saved backup.
    (
        set -o pipefail
        awk '
            {
                if (pending_vector_drop) {
                    if ($0 == "DROP EXTENSION IF EXISTS pg_search;") {
                        print
                        print "DROP EXTENSION IF EXISTS vector;"
                        pending_vector_drop = 0
                        next
                    }
                    print "DROP EXTENSION IF EXISTS vector;"
                    pending_vector_drop = 0
                }
                if ($0 == "DROP EXTENSION IF EXISTS vector;") {
                    pending_vector_drop = 1
                    next
                }
                if ($0 == "CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;") {
                    vector_created = 1
                }
                if ($0 == "CREATE EXTENSION IF NOT EXISTS pg_search WITH SCHEMA paradedb;" && !vector_created) {
                    print "CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;"
                    vector_created = 1
                }
                print
            }
            END {
                if (pending_vector_drop) print "DROP EXTENSION IF EXISTS vector;"
            }
        ' "$dump_file" | docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" \
            exec -T postgresql psql -v ON_ERROR_STOP=1 -U postgres -d "$LOBE_DB_NAME"
    )
}
