#!/bin/bash
# LobeHub - shared helpers

COMPOSE_PROJECT="lobehub_${app}"

# Docker Compose v2 binary path (installed via Docker CE official repo)
DOCKER_COMPOSE="docker compose"

gen_password() { openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 28; }
gen_secret()   { openssl rand -hex 16; }

build_app_url() {
    if [ "$path" = "/" ]; then
        APP_URL="https://${domain}"
    else
        APP_URL="https://${domain}${path}"
    fi
}

prepare_data_dirs() {
    mkdir -p "$data_dir/postgres"
    mkdir -p "$data_dir/rustfs"
    mkdir -p "$data_dir/redis"
    mkdir -p "$data_dir/searxng"

    chown -R "$app:$app" "$install_dir"
    chown -R "$app:$app" "$data_dir"

    # Official PostgreSQL and Redis containers run as numeric uid 999.
    chown -R 999:999 "$data_dir/postgres"
    chmod 700 "$data_dir/postgres"
    chown -R 999:999 "$data_dir/redis"
    chmod 750 "$data_dir/redis"

    # RustFS container runs as numeric uid 10001.
    chown -R 10001:10001 "$data_dir/rustfs"
    chmod 750 "$data_dir/rustfs"
}

# Remove stale PostgreSQL data directory if it was initialised by an
# incompatible upstream image (e.g. ParadeDB, which sets
# shared_preload_libraries = 'pg_search' in postgresql.conf). A leftover
# config from ParadeDB makes pgvector/pgvector crash on startup with
# FATAL: could not access file "pg_search".
clean_postgres_data_dir() {
    local pg_conf="$data_dir/postgres/postgresql.conf"
    if [ -f "$pg_conf" ] && grep -q "pg_search" "$pg_conf" 2>/dev/null; then
        ynh_print_warn "Found ParadeDB-era PostgreSQL config — wiping data directory so pgvector can re-init."
        systemctl stop "$app" 2>/dev/null || true
        rm -rf "$data_dir"/postgres/*
        chown -R 999:999 "$data_dir/postgres"
        chmod 700 "$data_dir/postgres"
    fi
}

write_env_file() {
    cat > "$install_dir/.env" << ENV_EOF
# LobeHub - auto-generated by YunoHost installer
# Do not edit manually.

APP_URL=${APP_URL}
LOBE_PORT=${port}
RUSTFS_PORT=${port_rustfs_api}
RUSTFS_ADMIN_PORT=${port_rustfs_console}

# Database
LOBE_DB_NAME=lobehub
POSTGRES_PASSWORD=${postgres_password}

# Auth / Security
KEY_VAULTS_SECRET=${key_vaults_secret}
AUTH_SECRET=${auth_secret}

# S3 / RustFS
RUSTFS_ACCESS_KEY=${rustfs_access_key}
RUSTFS_SECRET_KEY=${rustfs_secret_key}
RUSTFS_LOBE_BUCKET=lobe
S3_PUBLIC_DOMAIN=${APP_URL}/s3

# Admin credentials (first-run setup)
AUTH_ADMIN_EMAIL=${admin_email}
AUTH_ADMIN_PASSWORD=${admin_password}
ENV_EOF

    chmod 600 "$install_dir/.env"
    chown root:root "$install_dir/.env"
}

write_bucket_policy() {
    cat > "$install_dir/bucket.config.json" << 'BUCKET_EOF'
{
  "ID": "",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": ["*"]
      },
      "Action": ["s3:GetObject"],
      "NotAction": [],
      "Resource": ["arn:aws:s3:::lobe/*"],
      "NotResource": [],
      "Condition": {}
    }
  ],
  "Version": "2012-10-17"
}
BUCKET_EOF

    chown "$app:$app" "$install_dir/bucket.config.json"
    chmod 644 "$install_dir/bucket.config.json"
}

write_searxng_config() {
    # Ensure directory exists and is searchable
    mkdir -p "$data_dir/searxng"
    chown "$app:$app" "$data_dir/searxng"
    chmod 755 "$data_dir/searxng"

    cat > "$data_dir/searxng/settings.yml" << SEARXNG_EOF
use_default_settings: true

server:
  secret_key: "${searxng_secret}"
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"
  method: "POST"

search:
  safe_search: 0
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_theme: simple

outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
SEARXNG_EOF

    chown "$app:$app" "$data_dir/searxng/settings.yml"
    chmod 644 "$data_dir/searxng/settings.yml"
}


write_compose_file() {
    sed \
        -e "s|__APP__|${app}|g" \
        -e "s|__INSTALL_DIR__|${install_dir}|g" \
        -e "s|__DATA_DIR__|${data_dir}|g" \
        -e "s|__PORT__|${port}|g" \
        -e "s|__PORT_RUSTFS_API__|${port_rustfs_api}|g" \
        -e "s|__PORT_RUSTFS_CONSOLE__|${port_rustfs_console}|g" \
        ../conf/docker-compose.yml > "$install_dir/docker-compose.yml"

    chown root:root "$install_dir/docker-compose.yml"
}

wait_for_lobehub() {
    local elapsed=0
    local max_wait="${1:-600}"

    while [ "$elapsed" -lt "$max_wait" ]; do
        if curl -sf "http://127.0.0.1:${port}/" >/dev/null 2>&1; then
            ynh_print_info "LobeHub is up and running."
            return 0
        fi
        sleep 5
        elapsed=$((elapsed + 5))
    done

    # Health check failed — gather diagnostics
    ynh_print_warn "LobeHub did not respond on port ${port} within ${max_wait}s."
    ynh_print_warn "--- systemctl status $app ---"
    systemctl status "$app" --no-pager || true
    ynh_print_warn "--- journalctl (last 200 lines) ---"
    journalctl -u "$app" -n 200 --no-pager || true
    ynh_print_warn "--- docker compose ps -a ---"
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" ps -a || true
    ynh_print_warn "--- docker logs (postgresql) ---"
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 postgresql 2>&1 || \
        docker logs --tail=200 "${app}-postgres" 2>&1 || true
    ynh_print_warn "--- docker logs (lobe) ---"
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 lobe 2>&1 || \
        docker logs --tail=200 "${app}-lobe" 2>&1 || true
    ynh_print_warn "--- docker logs (rustfs-init) ---"
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" logs --tail=200 rustfs-init 2>&1 || \
        docker logs --tail=200 "${app}-rustfs-init" 2>&1 || true
    ynh_die "Health check timed out. Check: journalctl -u $app and docker compose logs"
}

install_docker_ce() {
    # Skip if docker compose v2 is already available (from any source)
    if docker compose version &>/dev/null 2>&1; then
        ynh_print_info "Docker Compose v2 already available: $(docker compose version --short)"
        return 0
    fi

    ynh_print_info "Installing Docker CE (official repo - provides Compose v2)..."

    # Add Docker's official GPG key (do NOT remove existing packages — other YunoHost apps may depend on them)
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable docker --quiet
    systemctl start docker

    # Verify
    docker compose version || ynh_die "Docker Compose v2 installation failed"
    ynh_print_info "Docker CE + Compose v2 installed: $(docker compose version)"
}

# Remove Docker images used by this app (called from remove script)
cleanup_docker_images() {
    local project="$app"
    ynh_print_info "Removing Docker images for project $project..."

    if [ -f "$install_dir/docker-compose.yml" ]; then
        cd "$install_dir"
        docker compose --project-name "$project" down --remove-orphans --volumes --timeout 30 || true
        docker compose --project-name "$project" rm -f || true
        # Remove images referenced in the compose file
        docker images --filter "reference=lobehub/lobehub*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=pgvector/pgvector*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=redis:*-alpine" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=rustfs/rustfs*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=minio/mc*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker images --filter "reference=searxng/searxng*" --format '{{.Repository}}:{{.Tag}}' | while read -r img; do
            docker rmi "$img" 2>/dev/null || true
        done
        docker image prune -f 2>/dev/null || true
    fi
}

# Dump PostgreSQL database via docker exec (consistent backup)
dump_postgres() {
    local dump_file="$1"
    ynh_print_info "Dumping PostgreSQL database..."
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" \
        exec -T postgresql pg_dump -U postgres -d "$LOBE_DB_NAME" --clean --if-exists > "$dump_file" 2>/dev/null
}

# Restore PostgreSQL database from dump
restore_postgres() {
    local dump_file="$1"
    if [ -f "$dump_file" ]; then
        ynh_print_info "Restoring PostgreSQL database from dump..."
        docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" \
            exec -T postgresql psql -U postgres -d "$LOBE_DB_NAME" < "$dump_file" 2>/dev/null || true
    fi
}
