#!/bin/bash
# LobeHub - shared helpers

COMPOSE_PROJECT="lobehub_${app}"

# Docker Compose v2 binary path (installed via Docker CE official repo)
DOCKER_COMPOSE="docker compose"

gen_password() { openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 28; }
gen_secret()   { openssl rand -hex 16; }

build_app_url() {
    if [ "$path" = "/" ]; then
        APP_URL="https://${domain}"
    else
        APP_URL="https://${domain}${path}"
    fi
}

prepare_data_dirs() {
    mkdir -p "$data_dir/postgres"
    mkdir -p "$data_dir/rustfs"
    mkdir -p "$data_dir/redis"
    mkdir -p "$data_dir/searxng"

    chown -R "$app:$app" "$install_dir"
    chown -R "$app:$app" "$data_dir"

    # Official PostgreSQL and Redis containers run as numeric uid 999.
    chown -R 999:999 "$data_dir/postgres"
    chmod 700 "$data_dir/postgres"
    chown -R 999:999 "$data_dir/redis"
    chmod 750 "$data_dir/redis"
}

write_env_file() {
    cat > "$install_dir/.env" << ENV_EOF
# LobeHub - auto-generated by YunoHost installer
# Do not edit manually.

APP_URL=${APP_URL}
LOBE_PORT=${port}
RUSTFS_PORT=${port_rustfs_api}
RUSTFS_ADMIN_PORT=${port_rustfs_console}

# Database
LOBE_DB_NAME=lobehub
POSTGRES_PASSWORD=${postgres_password}

# Auth / Security
KEY_VAULTS_SECRET=${key_vaults_secret}
AUTH_SECRET=${auth_secret}

# S3 / RustFS
RUSTFS_ACCESS_KEY=${rustfs_access_key}
RUSTFS_SECRET_KEY=${rustfs_secret_key}
RUSTFS_LOBE_BUCKET=lobe
S3_PUBLIC_DOMAIN=${APP_URL}/s3

# Admin credentials (first-run setup)
AUTH_ADMIN_EMAIL=${admin_email}
AUTH_ADMIN_PASSWORD=${admin_password}
ENV_EOF

    chmod 600 "$install_dir/.env"
    chown root:root "$install_dir/.env"
}

write_bucket_policy() {
    cat > "$install_dir/bucket.config.json" << 'BUCKET_EOF'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "AWS": ["*"] },
      "Action": ["s3:GetObject"],
      "Resource": ["arn:aws:s3:::lobe/*"]
    }
  ]
}
BUCKET_EOF

    chown "$app:$app" "$install_dir/bucket.config.json"
}

write_compose_file() {
    sed \
        -e "s|__APP__|${app}|g" \
        -e "s|__INSTALL_DIR__|${install_dir}|g" \
        -e "s|__DATA_DIR__|${data_dir}|g" \
        -e "s|__PORT__|${port}|g" \
        -e "s|__PORT_RUSTFS_API__|${port_rustfs_api}|g" \
        -e "s|__PORT_RUSTFS_CONSOLE__|${port_rustfs_console}|g" \
        ../conf/docker-compose.yml > "$install_dir/docker-compose.yml"

    chown root:root "$install_dir/docker-compose.yml"
}

wait_for_lobehub() {
    local elapsed=0
    local max_wait="${1:-600}"

    while [ "$elapsed" -lt "$max_wait" ]; do
        if curl -sf "http://127.0.0.1:${port}/" >/dev/null 2>&1; then
            ynh_print_info "LobeHub is up and running."
            return 0
        fi
        sleep 5
        elapsed=$((elapsed + 5))
    done

    systemctl status "$app" --no-pager || true
    journalctl -u "$app" -n 200 --no-pager || true
    docker compose --project-name "$app" --file "$install_dir/docker-compose.yml" ps -a || true
    docker logs --tail=200 "$app-lobe" || true
    docker logs --tail=200 "$app-rustfs-init" || true
    ynh_die "Health check timed out. Check: journalctl -u $app and docker logs $app-lobe"
}

install_docker_ce() {
    # Skip if docker compose v2 is already available
    if docker compose version &>/dev/null 2>&1; then
        ynh_print_info "Docker CE with Compose v2 already installed."
        return 0
    fi

    ynh_print_info "Installing Docker CE (official repo - provides Compose v2)..."

    # Remove old conflicting packages
    for pkg in docker.io docker-compose docker-doc podman-docker containerd runc; do
        apt-get remove -y "$pkg" 2>/dev/null || true
    done

    # Add Docker's official GPG key
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y --no-install-recommends \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable docker --quiet
    systemctl start docker

    # Verify
    docker compose version || ynh_die "Docker Compose v2 installation failed"
    ynh_print_info "Docker CE + Compose v2 installed: $(docker compose version)"
}
