#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping $app's systemd service..."
ynh_systemctl --service="$app" --action="stop"

ynh_script_progression "Updating NGINX web server configuration..."
ynh_config_change_url_nginx

ynh_script_progression "Rebuilding Lobe Chat for the new URL..."
build_lobechat

ynh_script_progression "Updating Lobe Chat environment..."
configure_lobechat_env

ynh_script_progression "Starting $app's systemd service..."
ynh_systemctl --service="$app" --action="start"

ynh_script_progression "Change of URL completed for $app"
