#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE CONTAINERS + IMAGES
#=================================================
ynh_script_progression --message="Stopping and removing Docker containers and images..." --weight=5

cleanup_docker_images

ynh_script_progression --message="LobeHub removed." --last
