#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE CONTAINERS
#=================================================
ynh_script_progression --message="Stopping and removing Docker containers..." --weight=5

if [ -f "$install_dir/docker-compose.yml" ]; then
    cd "$install_dir"
    docker compose --project-name "$app" down --remove-orphans --timeout 30 || true
fi

ynh_script_progression --message="LobeHub removed." --last
